development:
  adapter:  postgresql
  encoding: unicode
  database: pencetrips_dev
  username: appuser
  host:     localhost
  pool:     5

test: &test
  adapter:  postgresql
  encoding: unicode
  database: pencetrips_test
  username: appuser
  host:     localhost
  pool:     5

production:
  adapter:  postgresql
  encoding: unicode
  database: pencetrips
  username: appuser
  pool:     5
